name: Build and Deploy React Apps to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: my-kubernetes-codelab-1207
  GAR_LOCATION: asia-south2
  REPOSITORY: sumanart
  REGION: asia-south2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Configure Docker to use Google Cloud credentials
        run: |
          gcloud auth configure-docker "${{ env.GAR_LOCATION }}-docker.pkg.dev" --quiet

      - name: Build and push microfrontend container
        run: |
          cd microfrontend
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/microfrontend:latest" .
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/microfrontend:latest"

      - name: Build and push shell-pp container
        run: |
          cd shell-pp
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/shell-pp:latest" .
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/shell-pp:latest"

      - name: Deploy microfrontend to Cloud Run
        run: |
          gcloud run deploy microfrontend \
            --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/microfrontend:latest \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated

      - name: Deploy shell-pp to Cloud Run
        run: |
          gcloud run deploy shell-pp \
            --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/shell-pp:latest \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated